language: python
python:
  - 2.7
install:
  - pip install flake8 Django
before_script:
  - django-admin.py startproject --template=. testsite
script:
  - flake8 --max-line-length=125 --max-complexity=10 --statistics --benchmark testsite/testsite
  - cd testsite && pip install -q -r requirements.txt && python manage.py syncdb --noinput && python manage.py test
